# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

workflows: 
  version: 2
  builds:
    jobs:
      - build
  pass-all-tests:
    jobs:
      - test

jobs:
  build:
    docker:
      - image: circleci/golang:1.15.2
    steps:
      - checkout
      - run: go get -d ./...
      - run: go build ./...
  test:
    docker:
      - image: circleci/golang:1.15.2
    steps:
      - checkout
      - run: go get -d -t ./...
      - run: go test ./...
